services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Minsk
    volumes:
      - /docker/config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
