services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Minsk
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:sonarr
    volumes:
      - /docker/config/sonarr:/config
      - /data:/data
    ports:
      - 8989:8989
    restart: unless-stopped
