services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Minsk
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:radarr
    volumes:
      - /docker/config/radarr:/config
      - /data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
